[package]
name = "orx-pinned-vec"
version = "0.4.1"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "PinnedVec trait provides common vector functionalities with additional promises to preserve the memory locations of vector elements; i.e., to keep elements pinned in memory."
license = "MIT"
repository = "https://github.com/orxfun/orx-pinned-vec/"
keywords = ["vec", "array", "vector", "pinned", "memory"]
categories = ["data-structures"]

[dependencies]
